---
abstract: 'set of extensions for Perl6::Pod'
author:
  - 'Zahatski Aliaksandr zag@cpan.org'
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perl6-Pod-Lib
provides:
  Perl6::Pod::Lib:
    file: lib/Perl6/Pod/Lib.pm
    version: 0.12
  Perl6::Pod::Lib::Image:
    file: lib/Perl6/Pod/Lib/Image.pm
    version: 0
  Perl6::Pod::Lib::Include:
    file: lib/Perl6/Pod/Lib/Include.pm
    version: 0
requires:
  Perl6::Pod: 0.59
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Perl6::Pod::Lib
  license: http://dev.perl.org/licenses/
  repository: git://github.com/zag/p5-Perl6-Pod-Lib.git
version: 0.12
